export const data = [
  {
    order: 1,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'João Souza ',
    city: 'Pirapora',
    state: 'SP',
    points: 37,
  },
  {
    order: 2,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Carlos Batista',
    city: 'Rio de Janeiro',
    state: 'RJ',
    points: 30,
  },
  {
    order: 3,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Julia Ishimoto',
    city: 'São Paulo',
    state: 'SP',
    points: 25,
  },
  {
    order: 4,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Maria Ângela Santos',
    city: 'Foz do Iguaçu',
    state: 'PR',
    points: 23,
  },
  {
    order: 5,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Lucas Alves de Jesus',
    city: 'Rio de Janeiro',
    state: 'RJ',
    points: 22,
  },
  {
    order: 6,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Arthur Luz Almeida',
    city: 'São Paulo',
    state: 'SP',
    points: 21,
  },
  {
    order: 7,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Rogério Santos Sales',
    city: 'Sergipe',
    state: 'SE',
    points: 20,
  },
  {
    order: 8,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Erika Ferreira Lima',
    city: 'Osasco',
    state: 'SP',
    points: 19,
  },
  {
    order: 9,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Ricardo Mendes Gomes',
    city: 'Barueri',
    state: 'SP',
    points: 18,
  },
  {
    order: 10,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Silas Moreira',
    city: 'Palmas',
    state: 'TO',
    points: 17,
  },
  {
    order: 32,
    image: 'https://api.lorem.space/image/face?w=150&h=150',
    name: 'Você',
    city: 'Santana de Parnaíba',
    state: 'SP',
    points: 3,
  },
];
